### ISSUE TITLE
Noticable audio latency. snd_tmMixAhead=0.1 causes crash

### ISSUE THREAD

**Issue by LethalManBoob** [tx00100xt/SeriousSamClassic#5]
Perhaps somthing could be done about this?

**Comment by LethalManBoob** [comment]
I would like to add that selecting SDL_AUDIODRIVER=PIPEWIRE fixes the lag but causes the audio to be crusty on booting up. I need to change the khz to 22 from 44 and back again to fix this.

**Comment by tx00100xt** [comment]
I thought the game had nothing to do with it. It's more like system settings. Already a large number of people managed to launch the game, and no one spoke about problems with sound.

**Comment by LethalManBoob** [comment]
That would be very strange considering this is a vanilla install of pipewire with no changes and no such issue has ever occured on any other game or peice of software I use.

**Comment by LethalManBoob** [comment]
Alright it turns out setting snd_tmMixAhead=0.2 to a higher value does fix the lag. Im still confused why setting it lower than 0.2 causes a crash on alsa and pipewire and pulseaudio but i have fixed the issue. However the music being strange when not set to khz22 is maybe an issue but perhaps not fixable.

**Comment by tx00100xt** [comment]
I use Gentoo and don't use PipeWire.
PipeWire is unstable at the moment. https://wiki.gentoo.org/wiki/PipeWire
I will quote:
`Warning
As of mid 2022, PipeWire is still in active development. Some things may still not be fully integrated, tested, or implemented, and there may be large changes. It can work well for some, though the experience is not guaranteed to be perfect, free of issues, or bugs.`

` Important
This article currently describes the state-of-affairs in the [testing branch](https://wiki.gentoo.org/wiki/Handbook:X86/Portage/Branches#Testing) (~arch), rather than stable. This will change in future, once the pace of development slows down a bit.`

Perhaps the pipevare is still quite unstable. Once again I repeat the game has no problems with sound.
Look here: [Noticeable audio delay or audible pop/crack when starting playback](https://wiki.archlinux.org/title/PipeWire)

**Comment by LethalManBoob** [comment]
Well it seems im able to reduce the audio latency of alsa and pulse that it isnt so bad now. Pipewire still needs messing around in game to not crackle but everything seems much better now. thanks. Consider this closed. I suppose it makes sense since pipewire is indeed still very new.

**Comment by tx00100xt** [comment]
Good. I'm closing.
